
version: 2

models:
    - name: my_first_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: my_second_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

sources:
  - name: my_source
    database: TARGET_DB
    schema: DBT_PRACTICE
    tables:
      - name: bike 
        identifier: BIKE
      - name: weather
        identifier: WEATHER
